appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: ZjhqJVZRNiqheACRe0I7XyrEBW9YBnS80/QBoOioABN5DoydUq0W7sWaCSn7gSSNSSl+VD/ULmISYTf3TV6OjpLzHOWTeoLhv+0UJbgNCwLDYi1kELT0b1dK6FKKFiYfCfwdvnPsMIY3HbNaQmq7Y1y6CdaPmxXEoDBwbWHbVeEvCy+GgbJ0Pg/jJY6C+djDrueAK21vqoFby8kH0ZPg2j9d1m3oj7/ChwSsGNSvqwbb4gCQezTXir3uD6Tdgw054zl8f3vohaV3vLXu82R5gTkqfii8W21m1d21LO0rN5UzdULstPm28Ext/iTeXBj2HCTBXQM9DpU1S9s+9uxM9fZHKwVupAkPLnvQH7165VM88v6hiGv87o3gjLiCTwvueM6/u3O9E0bLiDJDvi4ZwddyjW/gosl09S4j3myMFOz6pHyv9Duv+kgs6Ps+D26dwMvEmkzO3Fw+W8iQcFij9PLyPo1JSPoQmMU00JfnxhiWc8BRlQyovB6M1hwxiY/UQF0GiaRuvcau447NZz7ommfYmsKfudfzpzv6CFIS+QB63+nE0hG32ozGRi0JpsQb8vk7BffaThItOHCwqMlCyBzezKvHh+mwVKmxwBCEUuUyyv0wAa/+5WuHJBLzA+FQHpdmoSXUs2kP7FLGUSK03aLM7ecejM89r0MUvtJc0eQ=}
provider:
  win: azure
bot:
  automerge: true
conda_forge_output_validation: true
